### ISSUE TITLE
Routing regression between 5.9.8 (Debian Bookworm deb12u1) and 5.9.13 (Ubuntu 24.04 (2ubuntu4))

### ISSUE THREAD

**Issue by marcust** [strongswan/strongswan#2230]
I upgraded to Ubuntu 24.04. yesterday (from 23.10, so I guess I was on 5.9.11-1ubuntu1.1), only to find out that VPN is not working anymore (e.g. already no name resolution on the DNS provided by the VPN, can't ping the DNS server). VPN is set up via Network Manager and uses charon-nm.

I see 
```
nm-xfrm-5040349: Local routing loop detected
```
in syslog, I also see
```
error uninstalling route installed with policy 172.29.4.6/32 === 0.0.0.0/0 out
```
when I disable the VPN connection again, I can't find this route before anywhere, not sure if that is related. 
I am not so close to routing, so I do not fully know what I would need to look for in my routing tables. I see that there are routing related changes in 5.9.12, I do not understand what was done there.

I _downgraded_ now to the Debian Bookworm packages which have 5.9.8 , and it works out of the box again. 

What additional information can I provide to help solve this issue?

**Comment by tobiasbrunner** [comment]
> I can't find this route before anywhere, not sure if that is related.

It should be in table 220 (`ip route list table 220`). And that table should only be used for traffic that is not marked with the value 220 (`ip rule`), which IKE as well as ESP packets should be. That is, these packets should not go via XFRM interface but via regular routing table/interfaces (thus avoiding the loop).

> What additional information can I provide to help solve this issue?

Logs by NetworkManager/charon-nm would be helpful (e.g. via `journalctl -u NetworkManager`).

**Comment by tobiasbrunner** [comment]
> Funnily enough table 220 does not even exist then

Obviously, as it's created by charon-nm ;)

That all looks fine so far. Traffic should be routed via XFRM interface, except for IKE and ESP packets (due to the mark they have applied) and packets destined to the subnets that got a throw routes installed (you probably have the _bypass-lan_ plugin enabled, which will install such routes for locally connected subnets).

You can check if the SAs look right via `ip -s xfrm state` (the mark should be mentioned, it also shows the traffic counters). But as I said, this all looks as it should. Do you still get `Local routing loop detected` errors? If so, for any particular traffic? (The other log message could be caused if the XFRM interface is deleted before the policy and route got uninstalled, this happens concurrently, as the latter will be gone then already.)

**Comment by tobiasbrunner** [comment]
Also, regarding DNS, did you configure `~.` as "additional search domain"? That's required to force DNS resolution via VPN.

**Comment by marcust** [comment]
> Obviously, as it's created by charon-nm ;) 
I was more saying that it is funny that the rule is already there, where does that come from then?

As far as I can see the `ip -s xfrm state` mentions the mark as `output-mark`. Not sure what else I read out of that. 

> Do you still get Local routing loop detected errors? If so, for any particular traffic? 

I see these messages all the time (155 messages for the last try, and that is without the `message repeated N times`), up to a point where I think it decides to kill the VPN afer a while (from the logs it looks like it reconnects because it can't reach something)?

```
charon-nm: 07[IKE] giving up after 5 retransmits
charon-nm: 07[IKE] peer not responding, trying again (2/0)
``` 

I guess the traffic is actually from the DNS also, because `resolved` complains that it is switching between TCP and UDP.

> Also, regarding DNS, did you configure ~. as "additional search domain"? That's required to force DNS resolution via VPN

That is only the initial symptom, but I can't even ping or dig directly at the nameservers. I can't reach anything inside the VPN network.

**Comment by tobiasbrunner** [comment]
> I was more saying that it is funny that the rule is already there, where does that come from then?

Oh, sorry, I missed that. Do you have any other IKE daemons running (charon-systemd, charon)? If so, disable them as that will definitely mess with the rule required by charon-nm (you could theoretically use other IKE daemons concurrently, but they have to be configured the same way for it to work).

**Comment by marcust** [comment]
That was apparently it.... 

Even though I am not 100% sure what fixed it now, I uninstalled a `strongswan-starter` and a `charon-systemd`. Now the existing rule after reboot is gone and everything works nicely again. Thanks for your help. 

I am just wondering if this used to be a combination that worked (because the ip rule was the same) and now stopped working if I am the only one who will hit that after upgrade.

**Comment by tobiasbrunner** [comment]
Yeah, I suppose this combination worked before [5.9.12](https://github.com/strongswan/strongswan/releases/tag/5.9.12) out of the box, as charon-nm did not actually use the XFRM interface (i.e. did not install special routes/marks etc.) or didn't use such interfaces at all. We should probably change the default routing table used by charon-nm to avoid that conflict. Just for reference, it's possible to change the table already via `charon-nm.routing_table` in strongswan.conf. I pushed a patch to the _2230-nm-routing-table_ branch.

**Comment by Jancis** [comment]
I have very similar issue and same error after fresh Ubuntu 24.04 install. Removing strongswan-starter and charon-systemd did not fix the issue.
I patched this by disabling disabling xfrm interface module and now it works, but it's not a proper solution -
> Edit /etc/strongswan.d/charon/kernel-netlink.conf and change `kernel-netlink.load = yes` to `no`.

**Comment by tobiasbrunner** [comment]
> Removing strongswan-starter and charon-systemd did not fix the issue.

Why not? What IKE daemon was still running (besides charon-nm)?

> I patched this by disabling disabling xfrm interface module and now it works, but it's not a proper solution -

Well, that basically prevents IKE daemons from starting (on Linux they require that plugin). Since charon-nm does not include these config snippets, it won't be affected, only the other ones. But yeah, that's not really a solution. Remove the IKE daemons if you don't need them, or change the routing table that charon-nm uses (see my last reply above).

**Comment by tarelda** [comment]
In my case, I have two VPNs that I use. One is IKEv2 and other is standard IKEv1/L2TP. 
After fresh upgrade to Ubuntu 24.04 only L2TP version worked. IKEv2 connected, but did not put rules to exempt traffic to VPN gateway, thus no connectivity. #2282 pointed me into looking at strongswan-starter package. As it turns out, stopping that systemd unit (strongswan-starter.service) allows to connect and setup IKEv2 connection successfully, but L2TP doesn't work anymore. Starting service fixes L2TP connection, but allowing strongswan-starter to do something unables to make IKEv2 work up until next reboot.

49cb7b0 seems like good fix, but underlying question is why Network Manager uses two separate ways of invoking charon for essentially differently configured IPSec VPNs?

**Comment by adrian-gheorghe** [comment]
Leaving this here for anyone that's running into the same issue I was (`nm-xfrm-8389435: Local routing loop detected!`)

To configure the vpn client on Ubuntu 24.04 desktop (with Gnome) only installing the `network-manager-strongswan` package was needed. 

Installing the network manager plugin alongside the charon-systemd or strongswan-starter (or strongswan metapackage) will lead to the above conflict/error

**Comment by elvisalicic** [comment]
Fedora 41 workstation connecting to IKEv2 VPN server here.

After installing NetworkManager-strongswan ( with strongswan and strongswan-charon-nm as dependencies ) I got the same "nm-xfrm-3880313: Local routing loop detected!"  loop.

Disabling strongswan systemd service "fixed" the issue.  I'll research the documentation a bit more during the work to figure out what is going on but I can work now.

**Comment by zimablu3** [comment]
> Leaving this here for anyone that's running into the same issue I was (`nm-xfrm-8389435: Local routing loop detected!`)
> 
> To configure the vpn client on Ubuntu 24.04 desktop (with Gnome) only installing the `network-manager-strongswan` package was needed.
> 
> Installing the network manager plugin alongside the charon-systemd or strongswan-starter running (or strongswan metapackage) will lead to the above conflict/error


you are not a friend
you are a mayor!!!

**Comment by kosuke-suzuki** [comment]
This thread really prevented me from wasting a day. Thank you!

**Comment by HarmtH** [comment]
> Leaving this here for anyone that's running into the same issue I was (`nm-xfrm-8389435: Local routing loop detected!`)
> 
> To configure the vpn client on Ubuntu 24.04 desktop (with Gnome) only installing the `network-manager-strongswan` package was needed.
> 
> Installing the network manager plugin alongside the charon-systemd or strongswan-starter running (or strongswan metapackage) will lead to the above conflict/error

Here (Ubuntu 24.04.2), trying to uninstall `strongswan-starter` would also uninstall `network-manager-strongswan`.

Turns out it was because some weird dependency links, namely `strongswan-starter (required by) strongswan (required by) network-manager-l2tp`

Luckily I don't need l2tp connections anymore, so after first removing `network-manager-l2tp` manually I could remove `strongswan-starter` without it resolving to `network-manager-strongswan` also having to be removed.
