### ISSUE TITLE
SA created but does not transmit user data if charon was restarted while route to peer was temporarily missing

### ISSUE THREAD

**Issue by xlapka01** [strongswan/strongswan#861]
**System (please complete the following information):**
 - OS: Embedded Linux 4.9.79 with Busybox
 - Kernel version (if applicable): Linux 4.9.79-ra2
 - strongSwan version(s): 5.9.4
 - Tested/confirmed with the latest version: yes (5.9.4)

**Describe the bug**
IPsec tunnel with IKEv2 is configured between 2 devices and transmits encrypted user data. One side reboots. After the reboot the deamon charon starts up and attempts to inititiate IKE SA, but there is no route to peer addres (either the interface is not up yet or dynamic routing is not yet stabilized). After the route to peer is obtained, charon will succeed to connect to the other side and open IKE SA and CHILD SA. However, encrypted traffic will not pass through. DPD queries are exchanged succesfully.
When receiving ESP packets on the side that disconnected, strange messages appear in charon log:
> 2022-01-24T07:20:04+00:00 03[ENC] no message rules specified for this message type
> 2022-01-24T07:20:04+00:00 03[NET] received unsupported IKE version 3.4 from 10.66.0.1, sending INVALID_MAJOR_VERSION

Issue will not resolve when CHILD SA is rekeyed. It will not resolve when IKE SA is rekeyed, unless reauthentication is forced (reauth_time). It will be resolved if IKE SA on either side is terminated manually through swanctl and then initialized. Turning on MOBIKE does not help. The issue does not occur when using IKEv1.

**To Reproduce**
1. Configue IPsec tunnel with IKEv2 between devices A and B, connected through interface "lan". A will act as a server (passive), B will connect SAs on startup.
2. Test that encrypted data pass through the tunnel.
3. On B: Close interface: ip link set dev lan down
4. On B: Check that there is no route to peer: ip route get <peerA>
5. On B: Restart charon daemon.
6. Wait 10s for charon to start and attempt to connect to peer.
7. On B: Reopen interface: ip link set dev lan up
8. On B: Wait for the tunnel to reestablish.
9. Check logs and swanctl on A and B to see that both IKE SA and CHILD SA were established.
10. Send data through the tunnel from A to B (for example ping). The data will not pass through, error messages will appear in log on B. 

Connection to peer can alternatively be disrupted by removing a routing rule instead of closing the interface.

**Expected behavior**
I expected that the tunnel would be established and able to pass encrypted data.
Or possibly that attempt to open IKE SA would fail with AUTHENTICATION_FAILED, as seen when there is some fallback routing rule during the restart (default GW routing peer address through wrong interface).

**Logs/Backtraces**
Logs and configuration are in attached package.
[issue_data.tar.gz](https://github.com/strongswan/strongswan/files/7924739/issue_data.tar.gz)

**Additional context**
This issue may occur on rebooting device with dynamic routing protocol, interfaces that use DHCP or that has to otherwise startup and connect to network (LTE, WiFi).

**Comment by tobiasbrunner** [comment]
It's a known problem with NAT detection, see e.g. https://github.com/strongswan/strongswan/discussions/708#discussioncomment-1586840.

When host B builds the IKE_SA_INIT request and the NAT-D payloads, it doesn't have the IP address it will later use to send the packet available yet. So when peer A receives the request, it detects a NAT situation because none of the NAT-D hashes matches to the source address from which the packet was eventually sent.

However, because the initiator does check the received NAT-D payloads against the destination address on which it received the  response, it won't detect a NAT on its end. So it won't switch to port 4500 to send IKE_AUTH and later doesn't install the CHILD_SA with UDP-encapsulation enabled. On the other hand, the responder will due to the NAT.

Such UDP-encapsulated ESP packets can't be accepted on port 500. Which is why you see the errors about invalid IKE messages. And even with a switch to port 4500 (as triggered by enabling MOBIKE) it won't work because the Linux kernel can't process UDP-encapsulated packets if encapsulation is not enabled for an SA (and vice-versa).

As discussed in https://github.com/strongswan/strongswan/discussions/708, enabling UDP-encapsulation is a workaround  (`encap=yes`). This sends a single fake `NATD_S_IP` payload to force the detection of a NAT situation (and, thus, enabling UDP-encapsulation on both sides). One of the proposed patches does this implicitly, however, it currently does it only if no local IP can be determined at all. It looks like this wouldn't help here as some addresses are available (host B sends two `NATD_S_IP` payloads). So even with that patch, you'd have to manually enable encapsulation. We could probably avoid that issue by removing the address enumeration (which also enumerates internal IPs). Not sure if the source IP enumeration is useful at all as it seems quite unlikely that the IP address would already be there but no route yet (the enumeration is from a time before we had a source address lookup via routing table, probably doesn't make much sense nowadays). An alternative workaround might be to cache all the sent `NATD_S_IP` hashes and compare them to the one we receive in the response and assume a NAT situation if none matches, which would basically have the same effect as forcing a NAT situation if we don't know the local address. In all these cases you'd end up with UDP-encapsulation for this SA, however, if encapsulation is not enforced via `encap=yes`, a MOBIKE update (either triggered by a route/address change or via DPD) could change that later.

**Comment by tobiasbrunner** [comment]
I've updated the patch in the _natd-fixes_ branch so the fallbacks (including the local address enumeration) are removed. So UDP-encapsulation should implicitly get enforced even in your scenario. If you enable MOBIKE, encap should get disabled again once no NAT is detected anymore.

**Comment by xlapka01** [comment]
Thank you. I will try it and let you know the result. It has not occurred to me that it may have a connection with NAT-D.

**Comment by xlapka01** [comment]
I have upgraded to 5.9.5 with patch from branch _natd-fixes_ (just file "src/libcharon/sa/ikev2/tasks/ike_natd.c"). I have run the test with bringing the interface down and restarting charon, as described above. I did it without MOBIKE and with MOBIKE. The problem remains in both cases.
I monitored the interface after SAs were reestablished and I sent ping from one side to the other to see how it will be encapsulated. Alfa denotes the peer that was stable, Alef denotes the peer that restarted without the route (interface down). Neither of test packets has passed through connection.
Without MOBIKE:
Alfa -> Alef:
> 08:17:02.728855 IP (tos 0x0, ttl 64, id 54891, offset 0, flags [DF], proto UDP (17), length 164)
>     10.66.0.1.500 > 10.66.0.6.500: isakmp 8.8 msgid bbfad5be:

  I would expect ESP in UDP encapsulation, based on your explanation. There are again error reports in logs on Alef (invalid IKE).

Alef -> Alfa:
> 08:18:01.966561 IP (tos 0x0, ttl 64, id 17544, offset 0, flags [DF], proto ESP (50), length 156)
>     10.66.0.6 > 10.66.0.1: ESP(spi=0xc7af2bca,seq=0x1), length 136

  Again, if I understand correctly, this should have been encapsulated in UDP.

With MOBIKE:
Alfa -> Alef:
> 08:23:41.908722 IP (tos 0x0, ttl 64, id 18490, offset 0, flags [DF], proto UDP (17), length 164)
>     10.66.0.1.4500 > 10.66.0.6.4500: UDP-encap: ESP(spi=0xc40e32da,seq=0x2), length 136

  As expected. But it is not decrypted on Alef, no reports in logs, same as in previous test with MOBIKE.

Alef -> Alfa:
> 08:25:08.287761 IP (tos 0x0, ttl 64, id 36402, offset 0, flags [DF], proto ESP (50), length 156)
>     10.66.0.6 > 10.66.0.1: ESP(spi=0xc17f52f1,seq=0x2), length 136

  I would expect it to be encapsulated in UDP.

According to the attached log, the condition was detected. There is a report:
> 2022-01-28T08:50:12022-01-28T08:50:16+00:00 06[IKE] <Conn0|1> unable to determine source address, faking NAT situation6+00:00 06[IKE] <Conn0|1> unable to determine source address, faking NAT situation

[Alef_charon_MOBIKE.log](https://github.com/strongswan/strongswan/files/7957170/Alef_charon_MOBIKE.log)

**Comment by tobiasbrunner** [comment]
You're right, there was still something missing. While the initiator now fakes a NAT situation, which the other peer detects, it didn't remember that it did that and, therefore, just checked the returned `NATD_S_IP` against the local address and didn't detect a NAT. I pushed an updated patch to the branch.

**Comment by xlapka01** [comment]
Thank you for the quick reaction.
The new patch is working.
Without MOBIKE: The SAs are reestablished, the test packets are passing in both directions as UDP-encapsulated ESP.
With MOBIKE: The SAs are reestablished, the test packet are passing in both directions as UDP-encapsulated ESP. This remains after DPD (INFORMATIONAL) exchange, CHILD SA rekeying and IKE SA rekeying. I have not attempted route or address change on my test setup.

The problem with unpassable connection seems to be solved. Thank you.

**Comment by tobiasbrunner** [comment]
Thanks for testing.

> This remains after DPD (INFORMATIONAL) exchange

Interesting. This might be due to `COND_NAT_FAKE` never actually getting removed once it has been set.  However, in this case it's only set on the initiator. The responder detected a NAT as usual, but shouldn't later on when DPDs are exchanged (you should see a log message there saying "remote host is not behind NAT anymore"). So I wonder if, after such a DPD and then rekeying the CHILD_SA, the UDP-encap state is still the same on both ends.

**Comment by xlapka01** [comment]
I have observed DPD exchange from both Alef (initiator of SAs) and Alfa. In neither case is encapsulation removed.
DPDs sent from Alfa:
Alfa:

> 2022-01-28T10:28:30+00:00 12[IKE] <Conn0|7> sending DPD request
> 2022-01-28T10:28:30+00:00 12[ENC] <Conn0|7> generating INFORMATIONAL request 0 [ ]
> 2022-01-28T10:28:30+00:00 12[NET] <Conn0|7> sending packet: from 10.66.0.1[4500] to 10.66.0.6[4500] (80 bytes)
> 2022-01-28T10:28:30+00:00 11[NET] <Conn0|7> received packet: from 10.66.0.6[4500] to 10.66.0.1[4500] (80 bytes)
> 2022-01-28T10:28:30+00:00 11[ENC] <Conn0|7> parsed INFORMATIONAL response 0 [ ]

Alef:

> 2022-01-28T10:27:02+00:00 08[NET] <Conn0|1> received packet: from 10.66.0.1[4500] to 10.66.0.6[4500] (80 bytes)
2022-01-28T10:27:02+00:00 08[ENC] <Conn0|1> parsed INFORMATIONAL request 0 [ ]
2022-01-28T10:27:02+00:00 08[ENC] <Conn0|1> generating INFORMATIONAL response 0 [ ]
2022-01-28T10:27:02+00:00 08[NET] <Conn0|1> sending packet: from 10.66.0.6[4500] to 10.66.0.1[4500] (80 bytes)

DPDs sent from Alef:
Alef:

> 2022-01-28T10:30:30+00:00 13[IKE] <Conn0|1> sending DPD request
2022-01-28T10:30:30+00:00 13[ENC] <Conn0|1> generating INFORMATIONAL request 2 [ ]
2022-01-28T10:30:30+00:00 13[NET] <Conn0|1> sending packet: from 10.66.0.6[4500] to 10.66.0.1[4500] (80 bytes)
2022-01-28T10:30:30+00:00 15[NET] <Conn0|1> received packet: from 10.66.0.1[4500] to 10.66.0.6[4500] (80 bytes)
2022-01-28T10:30:30+00:00 15[ENC] <Conn0|1> parsed INFORMATIONAL response 2 [ ]

Alfa:

> 2022-01-28T10:31:57+00:00 16[NET] <Conn0|2> received packet: from 10.66.0.6[4500] to 10.66.0.1[4500] (80 bytes)
2022-01-28T10:31:57+00:00 16[ENC] <Conn0|2> parsed INFORMATIONAL request 2 [ ]
2022-01-28T10:31:57+00:00 16[ENC] <Conn0|2> generating INFORMATIONAL response 2 [ ]
2022-01-28T10:31:57+00:00 16[NET] <Conn0|2> sending packet: from 10.66.0.1[4500] to 10.66.0.6[4500] (80 bytes)

Observed CHILD SA and IKE SA rekeying also preserved encapsulation.
The only message with "behind NAT" is on Alfa (stable side) when negotiating new connection after Alef was reconnected:

> 2022-01-28T10:31:22+00:00 16[IKE] <2> remote host is behind NAT

Full log excerpt of connection of SA reconnection on Alfa:

> 2022-01-28T10:31:21+00:00 16[NET] <2> received packet: from 10.66.0.6[500] to 10.66.0.1[500] (592 bytes)
2022-01-28T10:31:21+00:00 16[ENC] <2> parsed IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(REDIR_SUP) ]
2022-01-28T10:31:21+00:00 16[IKE] <2> 10.66.0.6 is initiating an IKE_SA
2022-01-28T10:31:21+00:00 16[CFG] <2> selected proposal: IKE:AES_CBC_128/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/MODP_3072
2022-01-28T10:31:22+00:00 16[IKE] <2> remote host is behind NAT
2022-01-28T10:31:22+00:00 16[ENC] <2> generating IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(CHDLESS_SUP) N(MULT_AUTH) ]
2022-01-28T10:31:22+00:00 16[NET] <2> sending packet: from 10.66.0.1[500] to 10.66.0.6[500] (600 bytes)
2022-01-28T10:31:22+00:00 05[NET] <2> received packet: from 10.66.0.6[4500] to 10.66.0.1[4500] (288 bytes)
2022-01-28T10:31:22+00:00 05[ENC] <2> parsed IKE_AUTH request 1 [ IDi N(INIT_CONTACT) IDr AUTH SA TSi TSr N(MOBIKE_SUP) N(ADD_4_ADDR) N(ADD_4_ADDR) N(MULT_AUTH) N(EAP_ONLY) N(MSG_ID_SYN_SUP) ]
2022-01-28T10:31:22+00:00 05[CFG] <2> looking for peer configs matching 10.66.0.1[AlfaV]...10.66.0.6[AlefV]
2022-01-28T10:31:22+00:00 05[CFG] <Conn0|2> selected peer config 'Conn0'
2022-01-28T10:31:22+00:00 05[IKE] <Conn0|2> authentication of 'AlefV' with pre-shared key successful
2022-01-28T10:31:22+00:00 05[IKE] <Conn0|2> peer supports MOBIKE, but disabled in config
2022-01-28T10:31:22+00:00 05[IKE] <Conn0|2> authentication of 'AlfaV' (myself) with pre-shared key
2022-01-28T10:31:22+00:00 05[IKE] <Conn0|1> destroying duplicate IKE_SA for peer 'AlefV', received INITIAL_CONTACT
2022-01-28T10:31:22+00:00 05[CHD] <Conn0|1> updown: charon.updown.evt.sh: ======= Connection Conn0_child0 is going DOWN =======
2022-01-28T10:31:22+00:00 05[IKE] <Conn0|2> IKE_SA Conn0[2] established between 10.66.0.1[AlfaV]...10.66.0.6[AlefV]
2022-01-28T10:31:22+00:00 05[IKE] <Conn0|2> scheduling rekeying in 291s
2022-01-28T10:31:22+00:00 05[IKE] <Conn0|2> maximum IKE_SA lifetime 321s
2022-01-28T10:31:22+00:00 05[CFG] <Conn0|2> selected proposal: ESP:AES_CBC_128/HMAC_SHA2_256_128/NO_EXT_SEQ
2022-01-28T10:31:22+00:00 05[KNL] <Conn0|2> HW offload is not supported by kernel
2022-01-28T10:31:22+00:00 05[KNL] <Conn0|2> HW offload is not supported by kernel
2022-01-28T10:31:22+00:00 05[IKE] <Conn0|2> CHILD_SA Conn0_child0{2} established with SPIs c21f01b7_i cab8f1ff_o and TS 192.168.1.11/32 === 192.168.6.66/32
2022-01-28T10:31:22+00:00 05[CHD] <Conn0|2> updown: charon.updown.evt.sh: ======= Connection Conn0_child0 is going UP =======
2022-01-28T10:31:22+00:00 05[ENC] <Conn0|2> generating IKE_AUTH response 1 [ IDr AUTH SA TSi TSr ]
2022-01-28T10:31:22+00:00 05[NET] <Conn0|2> sending packet: from 10.66.0.1[4500] to 10.66.0.6[4500] (224 bytes)

**Comment by xlapka01** [comment]
Ah, I apologise. There is an inconsistency in configuration of Alfa, it has deactivated MOBIKE. I will retry the test.

**Comment by xlapka01** [comment]
There appears to be no change. I have checked there is MOBIKE on both peers, but DPD exchanges look the same as the ones above.

**Comment by tobiasbrunner** [comment]
You're right, NAT-D notifies are currently only added by the initiator and only if it is behind an actual NAT, a fake NAT situation isn't considered. That's because the notifies are used to detect a change in the NAT mappings, which isn't necessary if there is only a fake NAT. So at least they wouldn't suddenly disagree.

That is, unless the responder sends its DPDs with NAT-D notifies (generally, doesn't make sense as responders are usually not behind dynamic NATs, but older strongSwan versions did that anyway). It would then not detect a NAT anymore and possibly switch off UDP-encap during the next CHILD_SA rekeying or MOBIKE update (it shouldn't do it immediately). We could avoid that by continuing to fake a NAT situation if `COND_NAT_FAKE` was enabled once.

The downside of that would be that UDP-encap wouldn't get switched off later, even if the initiator is not actually behind a NAT and the NAT situation was only forced because we didn't know the source IP initially. While MOBIKE updates sent after the local or remote address has changed do include NAT-D notifies even if there is no NAT (to detect a move from behind a NAT to a public IP or vice-versa), we'd obviously continue to detect a faked NAT.

What we could try is to not register this particular faked NAT as fake but as actual local NAT so initiated DPDs would include notifies because the NAT is now perceived as real. Since there is no actual NAT, the peers would detect that and the initiator would force a MOBIKE update to disable the UDP-encapsulation on the existing CHILD_SA. Well, not directly...

As mentioned above, the NAT-D notifies in DPDs are intended to detect changes in NAT mappings (i.e. the received hash for the local address/port is compared to a previous version to see if maybe a NAT router got restarted), not to detect if there is a NAT or not at all (which is very unlikely to change without a local or remote address changing, which would trigger a MOBIKE update containing NAT-D notifies instead). During a DPD, the code only triggers a MOBIKE update if the NAT mapping has changed. Now there is an interesting aspect to this.

MOBIKE has an inherent flaw with NAT-D. The initial NAT-D notifies are exchanged during IKE_SA_INIT. The problem is that the ports are then switched to 4500 to send IKE_AUTH. So any NAT-D hashes exchanged afterwards will never match those initial ones. We either always detect a difference and force a possibly gratuitous MOBIKE update after the first DPD, or we ignore the initial hash and cache the one received during the first DPD. strongSwan currently does the latter, assuming that there won't be a change in the NAT mappings until the first DPD is sent (this generally avoids an unnecessary MOBIKE update). However, in this scenario, it prevents the required MOBIKE update because the DPD that disables the NAT condition, only stores the hash but has none to compare it to. So here it would actually make sense to use the former approach, i.e. store the hash from IKE_SA_INIT (or any value really as there never will be a match) and let the first DPD sent by the initiator detect the change, which would then trigger a MOBIKE update for the established CHILD_SAs.

I've updated the commit in the branch accordingly.

**Comment by xlapka01** [comment]
I have tested the patch with MOBIKE On.
If the side that had no problem (Alfa) sends DPD, there is no change:

- It has recovered after startup with missing route to peer. It has started to encapsulate ESP to UDP.
- DPD (initiated from Alfa - passive side) has made no change in encapsulation.
- Rekeying CHILD SA has made no change in encapsulation
- Rekeying IKE SA (without reauthentication) has made no change in encapsulation.
- Difference: Alef (SA initiator) is now sending keepalive packets.

> 2022-01-31T07:23:42+00:00 07[IKE] <Conn0|1> sending keep alive to 10.66.0.1[4500]

> 07:25:13.708473 IP (tos 0x0, ttl 64, id 29408, offset 0, flags [DF], proto UDP (17), length 29)
    10.66.0.6.4500 > 10.66.0.1.4500: isakmp-nat-keep-alive

I am attaching a log from Alef (initiator of SAs, started without route to peer)
[Alef_charon_MOBIKE_patch2.log](https://github.com/strongswan/strongswan/files/7968821/Alef_charon_MOBIKE_patch2.log)
:

If Alef is starting DPD transactions instead of Alfa:

- It has recovered from missing route as before.
- The first DPD transaction started from Alef detects there is no NAT (reported only on the first DPD):

> 2022-01-31T07:23:52+00:00 09[IKE] <Conn0|1> sending DPD request
2022-01-31T07:23:52+00:00 09[ENC] <Conn0|1> generating INFORMATIONAL request 2 [ N(NATD_S_IP) N(NATD_D_IP) ]
2022-01-31T07:23:52+00:00 09[NET] <Conn0|1> sending packet: from 10.66.0.6[4500] to 10.66.0.1[4500] (128 bytes)
2022-01-31T07:23:52+00:00 10[NET] <Conn0|1> received packet: from 10.66.0.1[4500] to 10.66.0.6[4500] (128 bytes)
2022-01-31T07:23:52+00:00 10[ENC] <Conn0|1> parsed INFORMATIONAL response 2 [ N(NATD_S_IP) N(NATD_D_IP) ]
2022-01-31T07:23:52+00:00 10[IKE] <Conn0|1> local host is not behind NAT anymore

- The first CHILD SA rekeying will remove the encapsulation.

The behaviour therefore depends on which side initiates DPD transaction. I have DPD configured on both sides. For the sake of the test I set different timeouts to deterministically make one side an initiator. If I had the same timeouts on both sides, I presume one side would randomly take over sending DPDs, because receiving a DPD transaction resets peer's timer.

If I turn off DPD on both sides, encapsulation stays after CHILD SA rekeying (as expected from your explanation).

**Comment by tobiasbrunner** [comment]
Thanks again for testing.

> If the side that had no problem (Alfa) sends DPD, there is no change:

Yes, as I mentioned above, only a natted initiator sends NAT-D notifies in DPDs (older strongSwan versions did that differently, there, also responders added such notifies to DPDs).

> Difference: Alef (SA initiator) is now sending keepalive packets.

Yes, because it now thinks it is behind a real NAT.

> The first DPD transaction started from Alef detects there is no NAT (reported only on the first DPD):

The intention was to trigger a MOBIKE update to disable the encapsulation sooner. But I see now that there is an additional check that disables the check for changed NAT mappings if there is currently no NAT (I guess that makes sense). I've added a different trigger now (explicitly checking if a local NAT disappears), which should ensure a MOBIKE update disabled UDP-encap after the first DPD sent by the initiator.

> If I had the same timeouts on both sides, I presume one side would randomly take over sending DPDs, because receiving a DPD transaction resets peer's timer.

Correct.

> If I turn off DPD on both sides, encapsulation stays after CHILD SA rekeying (as expected from your explanation).

There are ways to trigger DPDs even if they are disabled (or the responder sends regular DPDs) e.g. by enabling _charon.check_current_path_, which initiates a DPD after local route/address events to verify that the current path is still usable. And enabling _charon.prefer_best_path_ could cause quicker MOBIKE updates if routes change.

**Comment by xlapka01** [comment]
OK, I have results from test with the new patch:
No change when DPD is initiated from Alfa (as expected).

If DPD is initiated from Alef, the first DPD detects that there is no NAT and encapsulation is immediately removed via MOBIKE update:

> 2022-01-31T10:33:56+00:00 09[IKE] <Conn0|1> sending DPD request
2022-01-31T10:33:56+00:00 09[ENC] <Conn0|1> generating INFORMATIONAL request 2 [ N(NATD_S_IP) N(NATD_D_IP) ]
2022-01-31T10:33:56+00:00 09[NET] <Conn0|1> sending packet: from 10.66.0.6[4500] to 10.66.0.1[4500] (128 bytes)
2022-01-31T10:33:56+00:00 10[NET] <Conn0|1> received packet: from 10.66.0.1[4500] to 10.66.0.6[4500] (128 bytes)
2022-01-31T10:33:56+00:00 10[ENC] <Conn0|1> parsed INFORMATIONAL response 2 [ N(NATD_S_IP) N(NATD_D_IP) ]
2022-01-31T10:33:56+00:00 10[IKE] <Conn0|1> local host is not behind NAT anymore
2022-01-31T10:33:56+00:00 10[IKE] <Conn0|1> detected changes in NAT mappings, initiating MOBIKE update
2022-01-31T10:33:56+00:00 10[ENC] <Conn0|1> generating INFORMATIONAL request 3 [ N(UPD_SA_ADDR) N(NATD_S_IP) N(NATD_D_IP) N(COOKIE2) ]
2022-01-31T10:33:56+00:00 10[NET] <Conn0|1> sending packet: from 10.66.0.6[4500] to 10.66.0.1[4500] (160 bytes)
2022-01-31T10:33:56+00:00 11[NET] <Conn0|1> received packet: from 10.66.0.1[4500] to 10.66.0.6[4500] (160 bytes)
2022-01-31T10:33:56+00:00 11[ENC] <Conn0|1> parsed INFORMATIONAL response 3 [ N(NATD_S_IP) N(NATD_D_IP) N(COOKIE2) ]

It is a pity that this mechanism relies on direction of DPD transactions. Since either side may, in general, start with no route to peer, I cannot make a configuration that will ensure that DPD will be sent the way that will later remove the encapsulation.
It is only a minor issue though, since the traffic is passing through.
Thank you for helping with this so actively.

**Comment by tobiasbrunner** [comment]
> If DPD is initiated from Alef, the first DPD detects that there is no NAT and encapsulation is immediately removed via MOBIKE update:

OK, great, thanks for the test.

> Since either side may, in general, start with no route to peer,

Only by the initiator will a NAT be faked in that situation as the responder won't be able to receive any messages until it has an IP/route, so whenever it generates NAT-D notifies it knows the actual IPs and does not have to resort to this workaround.

But yes, if it's only the responder who sends DPDs, UDP-encap won't be switched off until the initial CHILD_SA is rekeyed.

>  It is only a minor issue though, since the traffic is passing through.

I agree. But we could theoretically queue a MOBIKE-enabled DPD that gets exchanged right after the IKE_SA has been established (even if DPDs are disabled or would never get triggered because the peer always sends them earlier). I've pushed a couple of commits to the branch that implement that.

**Comment by xlapka01** [comment]
If there is well defined initiator, one can always set its DPD timeout shorter. This is what I did in my test. My concern was for the cases where both sides may initiate (both have start_action "start" or "trap").
Thank you for the new patch. I have run it through several tests. I added test without MOBIKE to test the new condition for planned DPD transaction.

Test with MOBIKE, DPD inititated by Alfa (stable):
- Startup (Alef):

> 2022-01-31T13:48:38+00:00 08[KNL] interface if_bridge.66 activated
2022-01-31T13:48:39+00:00 05[KNL] fe80::202:a9ff:fe20:5a1c appeared on if_bridge.66
2022-01-31T13:48:41+00:00 13[IKE] <Conn0|1> retransmit 3 of request with message ID 0
2022-01-31T13:48:41+00:00 13[NET] <Conn0|1> sending packet: from 0.0.0.0[500] to 10.66.0.1[500] (592 bytes)
2022-01-31T13:48:41+00:00 14[NET] <Conn0|1> received packet: from 10.66.0.1[500] to 10.66.0.6[500] (600 bytes)
2022-01-31T13:48:41+00:00 14[ENC] <Conn0|1> parsed IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(CHDLESS_SUP) N(MULT_AUTH) ]
2022-01-31T13:48:41+00:00 14[CFG] <Conn0|1> selected proposal: IKE:AES_CBC_128/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/MODP_3072
2022-01-31T13:48:42+00:00 14[IKE] <Conn0|1> local host is behind NAT, sending keep alives
2022-01-31T13:48:42+00:00 14[IKE] <Conn0|1> authentication of 'AlefV' (myself) with pre-shared key
2022-01-31T13:48:42+00:00 14[IKE] <Conn0|1> establishing CHILD_SA Conn0_child0{1}
2022-01-31T13:48:42+00:00 14[ENC] <Conn0|1> generating IKE_AUTH request 1 [ IDi N(INIT_CONTACT) IDr AUTH SA TSi TSr N(MOBIKE_SUP) N(ADD_4_ADDR) N(ADD_4_ADDR) N(ADD_4_ADDR) N(MULT_AUTH) N(EAP_ONLY) N(MSG_ID_SYN_SUP) ]
2022-01-31T13:48:42+00:00 14[NET] <Conn0|1> sending packet: from 10.66.0.6[4500] to 10.66.0.1[4500] (304 bytes)
2022-01-31T13:48:42+00:00 15[NET] <Conn0|1> received packet: from 10.66.0.1[4500] to 10.66.0.6[4500] (304 bytes)
2022-01-31T13:48:42+00:00 15[ENC] <Conn0|1> parsed IKE_AUTH response 1 [ IDr AUTH SA TSi TSr N(MOBIKE_SUP) N(ADD_4_ADDR) N(ADD_4_ADDR) N(ADD_4_ADDR) N(ADD_4_ADDR) N(ADD_4_ADDR) N(ADD_4_ADDR) N(ADD_4_ADDR) ]
2022-01-31T13:48:42+00:00 15[IKE] <Conn0|1> authentication of 'AlfaV' with pre-shared key successful
2022-01-31T13:48:42+00:00 15[IKE] <Conn0|1> IKE_SA Conn0[1] established between 10.66.0.6[AlefV]...10.66.0.1[AlfaV]
2022-01-31T13:48:42+00:00 15[IKE] <Conn0|1> scheduling rekeying in 283s
2022-01-31T13:48:42+00:00 15[IKE] <Conn0|1> maximum IKE_SA lifetime 313s
2022-01-31T13:48:42+00:00 15[CFG] <Conn0|1> selected proposal: ESP:AES_CBC_128/HMAC_SHA2_256_128/NO_EXT_SEQ
2022-01-31T13:48:42+00:00 15[KNL] <Conn0|1> HW offload is not supported by kernel
2022-01-31T13:48:42+00:00 15[KNL] <Conn0|1> HW offload is not supported by kernel
2022-01-31T13:48:42+00:00 15[IKE] <Conn0|1> CHILD_SA Conn0_child0{1} established with SPIs c1df6b4a_i c7e0346a_o and TS 192.168.6.66/32 === 192.168.1.11/32
2022-01-31T13:48:42+00:00 15[CHD] <Conn0|1> updown: charon.updown.evt.sh: ======= Connection Conn0_child0 is going UP =======
2022-01-31T13:48:42+00:00 15[IKE] <Conn0|1> peer supports MOBIKE
2022-01-31T13:48:42+00:00 15[ENC] <Conn0|1> generating INFORMATIONAL request 2 [ ]
2022-01-31T13:48:42+00:00 15[NET] <Conn0|1> sending packet: from 10.66.0.6[4500] to 10.66.0.1[4500] (80 bytes)
2022-01-31T13:48:42+00:00 06[NET] <Conn0|1> received packet: from 10.66.0.1[4500] to 10.66.0.6[4500] (80 bytes)
2022-01-31T13:48:42+00:00 06[ENC] <Conn0|1> parsed INFORMATIONAL response 2 [ ]

The new planned DPD transaction was executed, but it did not detect that NAT is not present. The traffic is encapsulated to UDP.

- DPD (from Alfa):

> 2022-01-31T13:49:02+00:00 09[IKE] <Conn0|1> sending keep alive to 10.66.0.1[4500]
2022-01-31T13:49:07+00:00 11[NET] <Conn0|1> received packet: from 10.66.0.1[4500] to 10.66.0.6[4500] (80 bytes)
2022-01-31T13:49:07+00:00 11[ENC] <Conn0|1> parsed INFORMATIONAL request 0 [ ]
2022-01-31T13:49:07+00:00 11[ENC] <Conn0|1> generating INFORMATIONAL response 0 [ ]
2022-01-31T13:49:07+00:00 11[NET] <Conn0|1> sending packet: from 10.66.0.6[4500] to 10.66.0.1[4500] (80 bytes)

No change, as expected.

Test with MOBIKE, DPD inititated by Alef (restarted):
- Startup (Alef) - effectively the same as previous test: DPD transaction is generated after SAs are established, it passes through, but does not detect that NAT is not present. Traffic is encapsulated.

> 2022-01-31T13:44:04+00:00 14[IKE] <Conn0|1> CHILD_SA Conn0_child0{1} established with SPIs c1990953_i c6cdb183_o and TS 192.168.6.66/32 === 192.168.1.11/32
2022-01-31T13:44:04+00:00 14[CHD] <Conn0|1> updown: charon.updown.evt.sh: ======= Connection Conn0_child0 is going UP =======
2022-01-31T13:44:04+00:00 14[IKE] <Conn0|1> peer supports MOBIKE
2022-01-31T13:44:04+00:00 14[ENC] <Conn0|1> generating INFORMATIONAL request 2 [ ]
2022-01-31T13:44:04+00:00 14[NET] <Conn0|1> sending packet: from 10.66.0.6[4500] to 10.66.0.1[4500] (80 bytes)
2022-01-31T13:44:04+00:00 16[NET] <Conn0|1> received packet: from 10.66.0.1[4500] to 10.66.0.6[4500] (80 bytes)
2022-01-31T13:44:04+00:00 16[ENC] <Conn0|1> parsed INFORMATIONAL response 2 [ ]

- 1st DPD from Alef correctly detects no NAT, encapsulation ends.

Test with MOBIKE, without DPD:
- Startup (Alef): SAs are established, planned DPD transaction is executed but does not detect there is no NAT. Traffic is encapsulated.

Test without MOBIKE, with DPD initiated by Alef (restarted):
- Startup (Alef):

> 2022-01-31T13:56:24+00:00 08[KNL] interface if_bridge.66 activated
2022-01-31T13:56:25+00:00 05[KNL] fe80::202:a9ff:fe20:5a1c appeared on if_bridge.66
2022-01-31T13:56:27+00:00 12[IKE] <Conn0|1> retransmit 3 of request with message ID 0
2022-01-31T13:56:27+00:00 12[NET] <Conn0|1> sending packet: from 0.0.0.0[500] to 10.66.0.1[500] (592 bytes)
2022-01-31T13:56:27+00:00 13[NET] <Conn0|1> received packet: from 10.66.0.1[500] to 10.66.0.6[500] (600 bytes)
2022-01-31T13:56:27+00:00 13[ENC] <Conn0|1> parsed IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(CHDLESS_SUP) N(MULT_AUTH) ]
2022-01-31T13:56:27+00:00 13[CFG] <Conn0|1> selected proposal: IKE:AES_CBC_128/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/MODP_3072
2022-01-31T13:56:28+00:00 13[IKE] <Conn0|1> local host is behind NAT, sending keep alives
2022-01-31T13:56:28+00:00 13[IKE] <Conn0|1> authentication of 'AlefV' (myself) with pre-shared key
2022-01-31T13:56:28+00:00 13[IKE] <Conn0|1> establishing CHILD_SA Conn0_child0{1}
2022-01-31T13:56:28+00:00 13[ENC] <Conn0|1> generating IKE_AUTH request 1 [ IDi N(INIT_CONTACT) IDr AUTH SA TSi TSr N(MULT_AUTH) N(EAP_ONLY) N(MSG_ID_SYN_SUP) ]
2022-01-31T13:56:28+00:00 13[NET] <Conn0|1> sending packet: from 10.66.0.6[4500] to 10.66.0.1[4500] (256 bytes)
2022-01-31T13:56:28+00:00 14[NET] <Conn0|1> received packet: from 10.66.0.1[4500] to 10.66.0.6[4500] (224 bytes)
2022-01-31T13:56:28+00:00 14[ENC] <Conn0|1> parsed IKE_AUTH response 1 [ IDr AUTH SA TSi TSr ]
2022-01-31T13:56:28+00:00 14[IKE] <Conn0|1> authentication of 'AlfaV' with pre-shared key successful
2022-01-31T13:56:28+00:00 14[IKE] <Conn0|1> IKE_SA Conn0[1] established between 10.66.0.6[AlefV]...10.66.0.1[AlfaV]
2022-01-31T13:56:28+00:00 14[IKE] <Conn0|1> scheduling rekeying in 298s
2022-01-31T13:56:28+00:00 14[IKE] <Conn0|1> maximum IKE_SA lifetime 328s
2022-01-31T13:56:28+00:00 14[CFG] <Conn0|1> selected proposal: ESP:AES_CBC_128/HMAC_SHA2_256_128/NO_EXT_SEQ
2022-01-31T13:56:28+00:00 14[KNL] <Conn0|1> HW offload is not supported by kernel
2022-01-31T13:56:28+00:00 14[KNL] <Conn0|1> HW offload is not supported by kernel
2022-01-31T13:56:28+00:00 14[IKE] <Conn0|1> CHILD_SA Conn0_child0{1} established with SPIs c567d266_i c6fa9785_o and TS 192.168.6.66/32 === 192.168.1.11/32
2022-01-31T13:56:28+00:00 14[CHD] <Conn0|1> updown: charon.updown.evt.sh: ======= Connection Conn0_child0 is going UP =======

This verifies that new DPD exchange does not happen when MOBIKE is disabled, because it is not supported.

- 1st regular DPD exchange from Alef: Does not detect missing NAT, as expected. 

It seems that patch correctly triggers the new DPD transaction when it should, but it does not detect that NAT is not present and so it has no effect on encapsulation.

**Comment by tobiasbrunner** [comment]
> This verifies that new DPD exchange does not happen when MOBIKE is disabled, because it is not supported.

Correct, without MOBIKE there will be no change. But that's not really an issue because without MOBIKE neither can detect that there is no NAT while the IKE_SA exists (i.e. until there is a reauthentication), so neither will disable UDP-encap unilaterally.

> It seems that patch correctly triggers the new DPD transaction when it should, but it does not detect that NAT is not present and so it has no effect on encapsulation.

Yeah, it's always those minor details :) I queued the task too early, i.e. before the actual NAT state was set, so it didn't create a sub-task for NAT-D. I've updated the last commit to fix that.

**Comment by xlapka01** [comment]
Thank you for the new patch. I have run it through the tests:

Test with MOBIKE, DPD initiated from Alfa (stable):
- Startup (Alef):

> 2022-02-01T07:00:23+00:00 08[KNL] interface if_bridge.66 activated
2022-02-01T07:00:25+00:00 05[KNL] fe80::202:a9ff:fe20:5a1c appeared on if_bridge.66
2022-02-01T07:00:26+00:00 12[IKE] <Conn0|1> retransmit 3 of request with message ID 0
2022-02-01T07:00:26+00:00 12[NET] <Conn0|1> sending packet: from 0.0.0.0[500] to 10.66.0.1[500] (592 bytes)
2022-02-01T07:00:27+00:00 13[NET] <Conn0|1> received packet: from 10.66.0.1[500] to 10.66.0.6[500] (600 bytes)
2022-02-01T07:00:27+00:00 13[ENC] <Conn0|1> parsed IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(CHDLESS_SUP) N(MULT_AUTH) ]
2022-02-01T07:00:27+00:00 13[CFG] <Conn0|1> selected proposal: IKE:AES_CBC_128/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/MODP_3072
2022-02-01T07:00:27+00:00 13[IKE] <Conn0|1> local host is behind NAT, sending keep alives
2022-02-01T07:00:27+00:00 13[IKE] <Conn0|1> authentication of 'AlefV' (myself) with pre-shared key
2022-02-01T07:00:27+00:00 13[IKE] <Conn0|1> establishing CHILD_SA Conn0_child0{1}
2022-02-01T07:00:27+00:00 13[ENC] <Conn0|1> generating IKE_AUTH request 1 [ IDi N(INIT_CONTACT) IDr AUTH SA TSi TSr N(MOBIKE_SUP) N(ADD_4_ADDR) N(ADD_4_ADDR) N(ADD_4_ADDR) N(MULT_AUTH) N(EAP_ONLY) N(MSG_ID_SYN_SUP) ]
2022-02-01T07:00:27+00:00 13[NET] <Conn0|1> sending packet: from 10.66.0.6[4500] to 10.66.0.1[4500] (304 bytes)
2022-02-01T07:00:27+00:00 14[NET] <Conn0|1> received packet: from 10.66.0.1[4500] to 10.66.0.6[4500] (304 bytes)
2022-02-01T07:00:27+00:00 14[ENC] <Conn0|1> parsed IKE_AUTH response 1 [ IDr AUTH SA TSi TSr N(MOBIKE_SUP) N(ADD_4_ADDR) N(ADD_4_ADDR) N(ADD_4_ADDR) N(ADD_4_ADDR) N(ADD_4_ADDR) N(ADD_4_ADDR) N(ADD_4_ADDR) ]
2022-02-01T07:00:27+00:00 14[IKE] <Conn0|1> authentication of 'AlfaV' with pre-shared key successful
2022-02-01T07:00:27+00:00 14[IKE] <Conn0|1> IKE_SA Conn0[1] established between 10.66.0.6[AlefV]...10.66.0.1[AlfaV]
2022-02-01T07:00:27+00:00 14[IKE] <Conn0|1> scheduling rekeying in 271s
2022-02-01T07:00:27+00:00 14[IKE] <Conn0|1> maximum IKE_SA lifetime 301s
2022-02-01T07:00:27+00:00 14[CFG] <Conn0|1> selected proposal: ESP:AES_CBC_128/HMAC_SHA2_256_128/NO_EXT_SEQ
2022-02-01T07:00:27+00:00 14[KNL] <Conn0|1> HW offload is not supported by kernel
2022-02-01T07:00:27+00:00 14[KNL] <Conn0|1> HW offload is not supported by kernel
2022-02-01T07:00:27+00:00 14[IKE] <Conn0|1> CHILD_SA Conn0_child0{1} established with SPIs cdb2047e_i cee121ae_o and TS 192.168.6.66/32 === 192.168.1.11/32
2022-02-01T07:00:27+00:00 14[CHD] <Conn0|1> updown: charon.updown.evt.sh: ======= Connection Conn0_child0 is going UP =======
2022-02-01T07:00:27+00:00 14[IKE] <Conn0|1> peer supports MOBIKE
2022-02-01T07:00:27+00:00 14[ENC] <Conn0|1> generating INFORMATIONAL request 2 [ N(NATD_S_IP) N(NATD_D_IP) ]
2022-02-01T07:00:27+00:00 14[NET] <Conn0|1> sending packet: from 10.66.0.6[4500] to 10.66.0.1[4500] (128 bytes)
2022-02-01T07:00:27+00:00 16[NET] <Conn0|1> received packet: from 10.66.0.1[4500] to 10.66.0.6[4500] (128 bytes)
2022-02-01T07:00:27+00:00 16[ENC] <Conn0|1> parsed INFORMATIONAL response 2 [ N(NATD_S_IP) N(NATD_D_IP) ]
2022-02-01T07:00:27+00:00 16[IKE] <Conn0|1> local host is not behind NAT anymore
2022-02-01T07:00:27+00:00 16[IKE] <Conn0|1> detected changes in NAT mappings, initiating MOBIKE update
2022-02-01T07:00:27+00:00 16[ENC] <Conn0|1> generating INFORMATIONAL request 3 [ N(UPD_SA_ADDR) N(NATD_S_IP) N(NATD_D_IP) N(COOKIE2) ]
2022-02-01T07:00:27+00:00 16[NET] <Conn0|1> sending packet: from 10.66.0.6[4500] to 10.66.0.1[4500] (160 bytes)
2022-02-01T07:00:27+00:00 06[NET] <Conn0|1> received packet: from 10.66.0.1[4500] to 10.66.0.6[4500] (160 bytes)
2022-02-01T07:00:27+00:00 06[ENC] <Conn0|1> parsed INFORMATIONAL response 3 [ N(NATD_S_IP) N(NATD_D_IP) N(COOKIE2) ]

User traffic is coming through, not encapsulated to UDP, in plain ESP. Further DPD transactions are normal.

Test with MOBIKE, DPD initiated from Alef (restarted):
Identical behavior. DPD transaction generated immediately after SAs are established, encapsulation is removed.

Test with MOBIKE, no DPD:
Identical behavior. DPD transaction generated immediately after SAs are established, encapsulation is removed.

Test without MOBIKE, DPD initiated from Alef (restarted):
Expected behavior, no DPD transaction on SA's startup, encapsulation is never removed.

It seems the patch is working as expected.

**Comment by tobiasbrunner** [comment]
Great, thanks again for these tests. I'll line these patches up for the next release.

**Comment by xlapka01** [comment]
Thanks for the help.
